apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster5
  region: ap-south-1

managedNodeGroups:
  - name: worker
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
  - name: egress-gw
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
    labels:
      io.cilium/egress-gateway: "true"
    taints:
      - key: egress-gw
        value: "true"
        effect: NoSchedule
    subnets:
      - subnet-#################
      - subnet-#################
      - subnet-#################