apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: efa-cluster
  region: us-west-2
  version: "1.29"

iam:
  withOIDC: true

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
  - name: my-efa-ng
    iam:
        attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    instanceType: g5.12xlarge
    minSize: 1
    desiredCapacity: 2
    maxSize: 2
    availabilityZones: ["us-west-2b"]
    volumeSize: 300
    privateNetworking: true
    efaEnabled: true
    # taint nodes so that application pods are
     # not scheduled/executed until Cilium is deployed.
     # Alternatively, see the note below.
    taints:
      - key: "node.cilium.io/agent-not-ready"
        value: "true"
        effect: "NoExecute"