apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: amit-6033
  region: ap-southeast-1

vpc:
  id: "vpc-039a8014ccd1bc5ce"
  subnets:
    private:
      ap-southeast-1a:
          id: "subnet-0ab37810d1901bb0e"
      ap-southeast-1b:
          id: "subnet-062a1b00c744fef3a"
      ap-southeast-1c:
          id: "subnet-0f33e4df743d1313b"
    public:
      ap-southeast-1a:
          id: "subnet-021d5c9b8fb06c7b5"
      ap-southeast-1b:
          id: "subnet-09ff93b4d244c70a4"
      ap-southeast-1c:
          id: "subnet-09b1cb3d62fc41576"

managedNodeGroups:
- name: ng-1
  iam:
     attachPolicyARNs:
       - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
       - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
       - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
       - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  desiredCapacity: 2
  privateNetworking: true
  # taint nodes so that application pods are
  # not scheduled/executed until Cilium is deployed.
  # Alternatively, see the note below.
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"