apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster5
  region: ap-south-1
  version: "1.30"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns