apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ipv6
  name: nginx-ipv6
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ipv6
  type: LoadBalancer